import { useAuth } from '@/contexts/auth'
import Head from 'next/head'

export default function Home() {
  const {isAuthenticated, user} = useAuth()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main 
      className='
      w-screen h-screen 
      flex flex-col justify-center items-center
      '>
        <h1 className='text-xl font-bold'>🚧Projeto em desenvolvimento🚧</h1>
        {isAuthenticated ? `bem vindo ${user?.name}` : ""}
      </main>
    </>
  )
}
