import { useAuth } from '@/contexts/auth'
import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main 
      className='
      w-screen h-screen 
      flex flex-col justify-center items-center
      '>
        <h1 className='text-xl font-bold'>🚧Projeto em desenvolvimento🚧</h1>
        <Link href="/app">app</Link>
      </main>
    </>
  )
}
